### PR TITLE
Move file function

### PR DESCRIPTION
**Pull request by krydos**
hi @licht1stein, 
thanks for the lib. 

A lot of time in obsidian I create a note in my inbox folder and then when I feel like it's completed I move it somewhere else with Obsidian's `Move current file to another folder` command. 
That's something I miss a lot in this lib so I added that function for myself. 

If you think it may be useful for you and others - feel free to merge then (let me know if I missed anything though, I'll update).

### CODE REVIEW

**Comment by licht1stein** [comment]
Hi @krydos thanks for the PR! I will fix the linting issues and merge it :)

**Comment by licht1stein** [comment]
I can't fix the linting issues myself, so in order to run all checks you need to install [eldev](https://github.com/doublep/eldev/) and run `make lint` in the obsidian.el folder.

**Comment by licht1stein** [comment]
Added a section https://github.com/licht1stein/obsidian.el#contributing

**Comment by krydos** [comment]
Thanks for the tips. 

installed eldev, fixed lint errors in obsidian.el file and squashed all those commits into one. 

I'm still getting lint errors locally in `obsidian.el-autoloads.el` and I'm unfortunately unfamiliar with how autoloads work and how that file is generated (I expect it is automatically generated). So if you see this error too, and if github workflow will see it, I'll try to understand autoloads better and fix it.

**Comment by licht1stein** [comment]
Thank you, @krydos, I really need to pay attention to my github notifications :)

**Pull request merged**
