### PR TITLE
Readme tweaks

### PR DESCRIPTION
**Pull request by netromdk**
I like to use [Hydra](https://github.com/abo-abo/hydra) menus and I made one for my own config that I wondered if you wanted on your README.

### CODE REVIEW

**Comment by licht1stein** [comment]
This is very cool. But I think it should be done within the code, with an optional binding to Hydra in readme. The code should be executed only if hydra is installed, similar to how the company-backend is added only if company is installed:

```elisp
(when (boundp 'hydra-verbose) ;; Something to tell us Hydra is installed
  (require 'hydra)
  (defhydra obsidian-hydra (:hint nil)
    "
Obsidian
_f_ollow at point   insert _w_ikilink          _q_uit
_j_ump to note      insert _l_ink
_t_ag find          _c_apture new note
_s_earch by expr.   _u_pdate tags/alises etc.
"
    ("c" obsidian-capture)
    ("f" obsidian-follow-link-at-point)
    ("j" obsidian-jump)
    ("l" obsidian-insert-link :color blue)
    ("q" nil :color blue)
    ("s" obsidian-search)
    ("t" obsidian-tag-find)
    ("u" obsidian-update)
    ("w" obsidian-insert-wikilink :color blue)))
```

And then simplify the example in the readme.

**Comment by netromdk** [comment]
Initially I just meant is as something people could easily make themselves as a customization. But that is a good idea to simply include it if Hydra is installed. I will make a change during today.

**Comment by licht1stein** [comment]
Great thanks!

**Comment by licht1stein** [comment]
Maybe we don't need a sepate readme snippet any more? We could just add it commented out to the existing use-package snippet, with a comment that if you have a hydra you can uncomment it. What do you think?

**Comment by licht1stein** [comment]
Otherwise ready to merge :)

**Comment by licht1stein** [comment]
Or even just put hydra binding as a separate line in a section of it's own

**Comment by netromdk** [comment]
I moved it to an individual section as you suggested. Is that fine? :-)

**Comment by netromdk** [comment]
Oh, are you using tabs instead of spaces? https://github.com/licht1stein/obsidian.el/runs/7828249758?check_suite_focus=true#step:6:11

I will change that.

**Comment by licht1stein** [comment]
I will fix the ilnt issues on separate branch, and then merge into master. Thanks!

**Comment by netromdk** [comment]
Alrighty. Thanks for the merge. :)

**Pull request merged**
